/**
 * ServiceCatalog Entity
 *
 * Represents a screening service/product (e.g., PRECA_BASIC, PRECA_PRO).
 * Following Clean Architecture: NO dependencies on external frameworks.
 */

import { FormSchema } from '../value-objects/FormSchema';
import { ReportSchema } from '../value-objects/ReportSchema';

export enum PersonType {
  PHYSICAL = 'physical',  // Individual person
  MORAL = 'moral'         // Company/organization
}

export interface ServiceCatalogProps {
  id: number;                // Auto-incremented ID (1, 2, 3...)
  code: string;              // Unique identifier (e.g., "PRECA_BASIC")
  name: string;              // Display name (e.g., "Precalificación Básica")
  description: string | null;
  priceMxn: number;          // Price in Mexican Pesos
  targetPersonType: PersonType;
  stripeProductId: string | null;  // Stripe Product ID
  stripePriceId: string | null;    // Stripe Price ID
  isActive: boolean;
  formSchema: FormSchema | null;   // Dynamic form schema for data collection
  reportSchema: ReportSchema | null; // Dynamic report schema for PDF generation
  requiresApplicantDetails: boolean;  // Whether service requires full applicant details
  createdAt: Date;
  updatedAt: Date;
}

export class ServiceCatalog {
  private constructor(private props: ServiceCatalogProps) {}

  // Factory method for creating a new service
  static create(
    code: string,
    name: string,
    priceMxn: number,
    targetPersonType: PersonType,
    description: string | null = null,
    stripeProductId: string | null = null,
    stripePriceId: string | null = null,
    formSchema: FormSchema | null = null,
    reportSchema: ReportSchema | null = null,
    requiresApplicantDetails: boolean = false
  ): ServiceCatalog {
    // Business rule: Code must be uppercase and alphanumeric with underscores
    if (!ServiceCatalog.isValidCode(code)) {
      throw new Error('Code must be uppercase alphanumeric with underscores (e.g., PRECA_BASIC)');
    }

    // Business rule: Name is required
    if (!name || name.trim().length === 0) {
      throw new Error('Service name is required');
    }

    // Business rule: Price must be positive
    if (priceMxn <= 0) {
      throw new Error('Price must be greater than zero');
    }

    // Business rule: Price must have max 2 decimal places
    if (!ServiceCatalog.isValidPrice(priceMxn)) {
      throw new Error('Price must have at most 2 decimal places');
    }

    return new ServiceCatalog({
      id: 0, // Will be auto-generated by database
      code: code.toUpperCase(),
      name: name.trim(),
      description: description?.trim() || null,
      priceMxn,
      targetPersonType,
      stripeProductId,
      stripePriceId,
      isActive: true,
      formSchema,
      reportSchema,
      requiresApplicantDetails,
      createdAt: new Date(),
      updatedAt: new Date()
    });
  }

  // Factory method for reconstituting from database
  static reconstitute(props: ServiceCatalogProps): ServiceCatalog {
    return new ServiceCatalog(props);
  }

  // Getters
  get id(): number { return this.props.id; }
  get code(): string { return this.props.code; }
  get name(): string { return this.props.name; }
  get description(): string | null { return this.props.description; }
  get priceMxn(): number { return this.props.priceMxn; }
  get targetPersonType(): PersonType { return this.props.targetPersonType; }
  get stripeProductId(): string | null { return this.props.stripeProductId; }
  get stripePriceId(): string | null { return this.props.stripePriceId; }
  get isActive(): boolean { return this.props.isActive; }
  get formSchema(): FormSchema | null { return this.props.formSchema; }
  get reportSchema(): ReportSchema | null { return this.props.reportSchema; }
  get requiresApplicantDetails(): boolean { return this.props.requiresApplicantDetails; }
  get createdAt(): Date { return this.props.createdAt; }
  get updatedAt(): Date { return this.props.updatedAt; }

  // Business methods
  updatePrice(newPrice: number): void {
    if (newPrice <= 0) {
      throw new Error('Price must be greater than zero');
    }

    if (!ServiceCatalog.isValidPrice(newPrice)) {
      throw new Error('Price must have at most 2 decimal places');
    }

    this.props.priceMxn = newPrice;
    this.props.updatedAt = new Date();
  }

  updateName(newName: string): void {
    if (!newName || newName.trim().length === 0) {
      throw new Error('Service name is required');
    }

    this.props.name = newName.trim();
    this.props.updatedAt = new Date();
  }

  updateDescription(newDescription: string | null): void {
    this.props.description = newDescription?.trim() || null;
    this.props.updatedAt = new Date();
  }

  deactivate(): void {
    this.props.isActive = false;
    this.props.updatedAt = new Date();
  }

  activate(): void {
    this.props.isActive = true;
    this.props.updatedAt = new Date();
  }

  updateStripeProductId(stripeProductId: string | null): void {
    this.props.stripeProductId = stripeProductId;
    this.props.updatedAt = new Date();
  }

  updateStripePriceId(stripePriceId: string | null): void {
    this.props.stripePriceId = stripePriceId;
    this.props.updatedAt = new Date();
  }

  updateFormSchema(formSchema: FormSchema | null): void {
    this.props.formSchema = formSchema;
    this.props.updatedAt = new Date();
  }

  updateReportSchema(reportSchema: ReportSchema | null): void {
    this.props.reportSchema = reportSchema;
    this.props.updatedAt = new Date();
  }

  setRequiresApplicantDetails(requires: boolean): void {
    this.props.requiresApplicantDetails = requires;
    this.props.updatedAt = new Date();
  }

  isLinkedToStripe(): boolean {
    return this.props.stripeProductId !== null && this.props.stripePriceId !== null;
  }

  hasFormSchema(): boolean {
    return this.props.formSchema !== null;
  }

  hasReportSchema(): boolean {
    return this.props.reportSchema !== null;
  }

  isForPhysicalPerson(): boolean {
    return this.props.targetPersonType === PersonType.PHYSICAL;
  }

  isForMoralPerson(): boolean {
    return this.props.targetPersonType === PersonType.MORAL;
  }

  // Formatted price for display (e.g., "$299.00 MXN")
  getFormattedPrice(): string {
    return `$${this.props.priceMxn.toFixed(2)} MXN`;
  }

  // Helper methods
  private static isValidCode(code: string): boolean {
    const codeRegex = /^[A-Z0-9_]+$/;
    return codeRegex.test(code);
  }

  private static isValidPrice(price: number): boolean {
    // Check if price has at most 2 decimal places
    return Number.isFinite(price) && Math.round(price * 100) === price * 100;
  }

  // Convert to plain object (for serialization)
  toObject(): ServiceCatalogProps {
    return { ...this.props };
  }
}
